@section('layoutsObj')
    <script type="text/javascript">
        var layoutsObj = {
            js_plan1: {
                name: 'Помещение на первом этаже',
                desc: 'Пример использования под автомойку',
                area: '157,1',
                price: '43 988 000',
                block_location: '/img/block_e.png',
                floor1_2d: '/img/91,9.png',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '',
                file: ''
            },
            js_plan2: {
                name: 'Помещение на первом этаже',
                desc: 'Пример использования под автосалон',
                area: '152,8',
                price: '42 784 000',
                block_location: '/img/block_j.png',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '',
                file: ''
            },
            js_plan3: {
                name: 'Помещение на втором этаже',
                desc: 'Пример использования под клинику',
                area: '253,8',
                price: '71 064 000',
                block_location: '/img/block_b.png',
                floor1_2d: '/img/253,8.png',
                floor1_3d: '/img/spa_3d.png',
                floor1_3d_big: '/img/spa_3d.png',
                floor2_2d: '',
                file: ''
            },
            js_plan4: {
                name: 'Помещение на первом этаже',
                desc: 'Пример использования под кофейню',
                area: '128,5',
                price: '35 980 000',
                block_location: '/img/block_i.png',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '',
                file: ''
            },
            js_plan5: {
                name: 'Помещение на втором этаже',
                desc: 'Пример использования под коворкинг',
                area: '206,8',
                price: '57 904 000',
                block_location: '/img/block_e.png',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '',
                file: ''
            },
            js_plan6: {
                name: 'Двухэтажное помещение',
                desc: 'Пример использования под детский сад',
                area: '258,4',
                price: '72 352 000',
//                block_location: '/img/block_g.png',
                block_location: '/img/block_e.png',
                floor1_2d: '/img/327,5.png',
                floor1_3d: '/img/restauran1_3d.png',
                floor1_3d_big: '/img/b_restauran1_3d.png',
                floor2_2d: '/img/327,5_2.png',
                floor2_3d: '/img/restauran2_3d.png',
                floor2_3d_big: '/img/b_restauran2_3d.png',
                file: ''
            },
            js_plan7: {
                name: 'Помещение на втором этаже',
                desc: 'Пример использования под типографию',
                area: '199,1',
                price: '55 748 000',
                block_location: '/img/block_j.png',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '',
                file: ''
            },
            js_plan8: {
                name: 'Помещение на втором этаже',
                desc: 'Пример использования под офисное помещение',
                area: '199,7',
                price: '55 916 000',
                block_location: '/img/block_j.png',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '',
                file: ''
            },
            js_plan9: {
                name: 'Двухэтажное помещение',
                desc: 'Пример использования под мебельный магазин',
                area: '353,5',
                price: '98 980 000',
                block_location: '/img/block_g.png',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '/img/',
                floor2_3d: '/img/',
                floor2_3d_big: '/img/',
                file: ''
            },
            js_plan10: {
                name: 'Двухэтажное помещение',
                desc: 'Пример использования под магазин техники',
                area: '327,5',
                price: '91 700 000',
                block_location: '/img/block_e.png',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '/img/',
                floor2_3d: '/img/',
                floor2_3d_big: '/img/',
                file: ''
            },
            js_plan11: {
                name: 'Помещение на втором этаже',
                desc: 'Пример использования под парфюмерный магазин',
                area: '217',
                price: '60 760 000',
                block_location: '/img/block_i.png',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '',
                file: ''
            },
            js_plan12: {
                name: 'Двухэтажное помещение',
                desc: 'Пример использования под сеть столовых',
                area: '296,9',
                price: '83 132 000',
                block_location: '/img/block_d.png',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '/img/',
                floor2_3d: '/img/',
                floor2_3d_big: '/img/',
                file: ''
            },
            js_plan13: {
                name: 'Помещение на втором этаже',
                desc: 'Пример использования под спа салон',
                area: '144',
                price: '40 320 000',
                block_location: '/img/block_d.png',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '',
                file: ''
            },
            js_plan14: {
                name: 'Двухэтажное помещение',
                desc: 'Пример использования под тренажерный зал',
                area: '1093',
                price: '306 258 400',
                block_location: '',
                floor1_2d: '/img/',
                floor1_3d: '/img/',
                floor1_3d_big: '/img/',
                floor2_2d: '/img/',
                floor2_3d: '/img/',
                floor2_3d_big: '/img/',
                file: ''
            }
        };
    </script>
@endsection